default_stages: [commit, push]

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, "lf"]
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-docstring-first
      - id: sort-simple-yaml
      - id: file-contents-sorter
      - id: check-builtin-literals

  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
        args:
          [
            --exit-zero-even-if-changed,
            --application-directories,
            ".:poker_gym",
            --py310-plus,
            --add-import,
            "from __future__ import annotations",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.941"
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-simplify

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint

  - repo: local
    hooks:
      # - id: pytest
      #   name: pytest
      #   language: system
      #   entry: pytest
      #   types: [python]
      #   pass_filenames: false
      #   fail_fast: true
      #   always_run: true

      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate config
        entry: poetry check
        language: python
        language_version: python3
        pass_filenames: false
        files: ^pyproject.toml$
